name: "Prepare documentation context"
description: "Select candidate documentation files and build context payloads for Codex."
inputs:
  doc-globs:
    description: "Newline-delimited globs that represent documentation files."
    required: false
    default: |
      docs/**/*.md
      docs/**/*.mdx
      docs/**/*.rst
      docs/**/*.adoc
      README.md
      *.md
      *.mdx
      *.rst
  changed-files-path:
    description: "Path to the newline-delimited list of changed files from the PR diff."
    required: true
  max-doc-files:
    description: "Maximum number of documentation files to include in the prompt context."
    required: false
    default: "12"
  max-doc-chars:
    description: "Maximum number of characters to include per documentation file excerpt."
    required: false
    default: "6000"
  max-total-chars:
    description: "Maximum total characters across all doc excerpts."
    required: false
    default: "60000"
  context-path:
    description: "Desired output path for the generated documentation context markdown."
    required: false
    default: "doc-context.md"
  allowlist-path:
    description: "Path where the doc allowlist JSON will be written."
    required: false
    default: "doc-allowlist.json"
outputs:
  doc_context_path:
    description: "Path to the markdown file containing selected doc excerpts."
    value: ${{ steps.prepare.outputs.doc_context_path }}
  doc_allowlist_path:
    description: "Path to the JSON file listing all documentation files allowed for edits."
    value: ${{ steps.prepare.outputs.doc_allowlist_path }}
runs:
  using: "composite"
  steps:
    - id: prepare
      name: Build documentation context
      shell: bash
      env:
        DOC_GLOBS: ${{ inputs.doc-globs }}
        CHANGED_FILES_PATH: ${{ inputs.changed-files-path }}
        MAX_DOC_FILES: ${{ inputs.max-doc-files }}
        MAX_DOC_CHARS: ${{ inputs.max-doc-chars }}
        MAX_TOTAL_CHARS: ${{ inputs.max-total-chars }}
        CONTEXT_PATH: ${{ inputs.context-path }}
        ALLOWLIST_PATH: ${{ inputs.allowlist-path }}
      run: |
        set -euo pipefail
        python "$GITHUB_ACTION_PATH/../lib/build-doc-context.py"
