name: "Apply Codex auto-labels"
description: "Create missing labels via gh CLI and apply them to the issue."
inputs:
  github-token:
    description: "GitHub token with repo scope."
    required: true
  max-labels:
    description: "Maximum number of labels to apply."
    required: true
runs:
  using: "composite"
  steps:
    - name: Delegate to shared action implementation
      uses: ../../actions/auto-label/apply
      with:
        github-token: ${{ inputs.github-token }}
        max-labels: ${{ inputs.max-labels }}
