name: "Prepare Codex auto-label assets"
description: "Clamp max labels, fetch repository label metadata, and build the Codex prompt/schema files."
inputs:
  max-labels:
    description: "Requested maximum number of labels (1-3)."
    required: false
    default: "3"
  github-token:
    description: "GitHub token with repo scope for label metadata."
    required: true
outputs:
  max-labels:
    description: "Clamped max label count."
    value: ${{ steps.bounds.outputs.max }}
  codex-output-schema:
    description: "JSON schema for Codex label output."
    value: ${{ steps.schema.outputs.schema }}
runs:
  using: "composite"
  steps:
    - name: Delegate to shared action implementation
      uses: ../../actions/auto-label/prepare
      with:
        max-labels: ${{ inputs.max-labels }}
        github-token: ${{ inputs.github-token }}
